# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rating', models.IntegerField()),
                ('max_rating', models.IntegerField()),
                ('type', models.CharField(choices=[('national', 'national'), ('international', 'international')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('professors', models.IntegerField(blank=True, null=True)),
                ('students', models.IntegerField(blank=True, null=True)),
                ('doctors', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University'),
        ),
        migrations.AddField(
            model_name='rating',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University'),
        ),
        migrations.AddField(
            model_name='direction',
            name='bachelor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bachelor', to='core.University'),
        ),
        migrations.AddField(
            model_name='direction',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='core.University'),
        ),
        migrations.AddField(
            model_name='direction',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='core.University'),
        ),
    ]
